const placeTypes = [
  { "key": "car_dealer", "value": "Araba Bayisi" },
  { "key": "car_rental", "value": "Araba Kiralama" },
  { "key": "car_repair", "value": "Araba Tamiri" },
  { "key": "car_wash", "value": "Araba Yıkama" },
  { "key": "electric_vehicle_charging_station", "value": "Elektrikli Araç Şarj İstasyonu" },
  { "key": "gas_station", "value": "Benzin İstasyonu" },
  { "key": "parking", "value": "Otopark" },
  { "key": "rest_stop", "value": "Dinlenme Tesisi" },
  { "key": "corporate_office", "value": "Kurumsal Ofis" },
  { "key": "farm", "value": "Çiftlik" },
  { "key": "ranch", "value": "Çiftlik Evi" },
  { "key": "art_gallery", "value": "Sanat Galerisi" },
  { "key": "art_studio", "value": "Sanat Stüdyosu" },
  { "key": "auditorium", "value": "Oditoryum" },
  { "key": "cultural_landmark", "value": "Kültürel Anıt" },
  { "key": "historical_place", "value": "Tarihi Mekan" },
  { "key": "monument", "value": "Anıt" },
  { "key": "museum", "value": "Müze" },
  { "key": "performing_arts_theater", "value": "Sahne Sanatları Tiyatrosu" },
  { "key": "sculpture", "value": "Heykel" },
  { "key": "library", "value": "Kütüphane" },
  { "key": "preschool", "value": "Anaokulu" },
  { "key": "primary_school", "value": "İlkokul" },
  { "key": "secondary_school", "value": "Ortaokul" },
  { "key": "university", "value": "Üniversite" },
  { "key": "adventure_sports_center", "value": "Macera Sporları Merkezi" },
  { "key": "amphitheatre", "value": "Amfi Tiyatro" },
  { "key": "amusement_center", "value": "Eğlence Merkezi" },
  { "key": "amusement_park", "value": "Lunapark" },
  { "key": "aquarium", "value": "Akvaryum" },
  { "key": "banquet_hall", "value": "Ziyafet Salonu" },
  { "key": "barbecue_area", "value": "Mangal Alanı" },
  { "key": "botanical_garden", "value": "Botanik Bahçesi" },
  { "key": "bowling_alley", "value": "Bowling Salonu" },
  { "key": "casino", "value": "Kumarhane" },
  { "key": "childrens_camp", "value": "Çocuk Kampı" },
  { "key": "comedy_club", "value": "Komedi Kulübü" },
  { "key": "community_center", "value": "Toplum Merkezi" },
  { "key": "concert_hall", "value": "Konser Salonu" },
  { "key": "convention_center", "value": "Kongre Merkezi" },
  { "key": "cultural_center", "value": "Kültür Merkezi" },
  { "key": "cycling_park", "value": "Bisiklet Parkı" },
  { "key": "dance_hall", "value": "Dans Salonu" },
  { "key": "dog_park", "value": "Köpek Parkı" },
  { "key": "event_venue", "value": "Etkinlik Mekanı" },
  { "key": "public_bath", "value": "Halk Hamamı" },
  { "key": "public_bathroom", "value": "Halka Açık Tuvalet" },
  { "key": "stable", "value": "Ahır" },
  { "key": "accounting", "value": "Muhasebe" },
  { "key": "atm", "value": "ATM" },
  { "key": "bank", "value": "Banka" },
  { "key": "acai_shop", "value": "Acai Dükkanı" },
  { "key": "afghani_restaurant", "value": "Afgan Restoranı" },
  { "key": "african_restaurant", "value": "Afrika Restoranı" },
  { "key": "american_restaurant", "value": "Amerikan Restoranı" },
  { "key": "asian_restaurant", "value": "Asya Restoranı" },
  { "key": "bagel_shop", "value": "Bagel Dükkanı" },
  { "key": "bakery", "value": "Fırın" },
  { "key": "bar", "value": "Bar" },
  { "key": "bar_and_grill", "value": "Bar ve Izgara" },
  { "key": "barbecue_restaurant", "value": "Barbekü Restoranı" },
  { "key": "brazilian_restaurant", "value": "Brezilya Restoranı" },
  { "key": "breakfast_restaurant", "value": "Kahvaltı Restoranı" },
  { "key": "brunch_restaurant", "value": "Brunch Restoranı" },
  { "key": "buffet_restaurant", "value": "Açık Büfe Restoran" },
  { "key": "cafe", "value": "Kafe" },
  { "key": "cafeteria", "value": "Kafeterya" },
  { "key": "candy_store", "value": "Şekerci Dükkanı" },
  { "key": "cat_cafe", "value": "Kedi Kafesi" },
  { "key": "chinese_restaurant", "value": "Çin Restoranı" },
  { "key": "chocolate_factory", "value": "Çikolata Fabrikası" },
  { "key": "chocolate_shop", "value": "Çikolata Dükkanı" },
  { "key": "coffee_shop", "value": "Kahve Dükkanı" },
  { "key": "confectionery", "value": "Pastane" },
  { "key": "deli", "value": "Şarküteri" },
  { "key": "dessert_restaurant", "value": "Tatlı Restoranı" },
  { "key": "dessert_shop", "value": "Tatlıcı" },
  { "key": "diner", "value": "Lokanta" },
  { "key": "dog_cafe", "value": "Köpek Kafesi" },
  { "key": "donut_shop", "value": "Donut Dükkanı" },
  { "key": "fast_food_restaurant", "value": "Fast Food Restoranı" },
  { "key": "fine_dining_restaurant", "value": "Lüks Restoran" },
  { "key": "food_court", "value": "Yemek Katı" },
  { "key": "french_restaurant", "value": "Fransız Restoranı" },
  { "key": "greek_restaurant", "value": "Yunan Restoranı" },
  { "key": "hamburger_restaurant", "value": "Hamburger Restoranı" },
  { "key": "ice_cream_shop", "value": "Dondurmacı" },
  { "key": "indian_restaurant", "value": "Hint Restoranı" },
  { "key": "italian_restaurant", "value": "İtalyan Restoranı" },
  { "key": "japanese_restaurant", "value": "Japon Restoranı" },
  { "key": "juice_shop", "value": "Meyve Suyu Dükkanı" },
  { "key": "korean_restaurant", "value": "Kore Restoranı" },
  { "key": "lebanese_restaurant", "value": "Lübnan Restoranı" },
  { "key": "meal_delivery", "value": "Yemek Teslimatı" },
  { "key": "meal_takeaway", "value": "Paket Servis" },
  { "key": "mediterranean_restaurant", "value": "Akdeniz Restoranı" },
  { "key": "mexican_restaurant", "value": "Meksika Restoranı" },
  { "key": "middle_eastern_restaurant", "value": "Orta Doğu Restoranı" },
  { "key": "pizza_restaurant", "value": "Pizza Restoranı" },
  { "key": "pub", "value": "Pub" },
  { "key": "ramen_restaurant", "value": "Ramen Restoranı" },
  { "key": "restaurant", "value": "Restoran" },
  { "key": "sandwich_shop", "value": "Sandviç Dükkanı" },
  { "key": "seafood_restaurant", "value": "Deniz Ürünleri Restoranı" },
  { "key": "spanish_restaurant", "value": "İspanyol Restoranı" },
  { "key": "steak_house", "value": "Steakhouse" },
  { "key": "sushi_restaurant", "value": "Suşi Restoranı" },
  { "key": "tea_house", "value": "Çay Evi" },
  { "key": "thai_restaurant", "value": "Tayland Restoranı" },
  { "key": "turkish_restaurant", "value": "Türk Restoranı" },
  { "key": "vegan_restaurant", "value": "Vegan Restoranı" },
  { "key": "vegetarian_restaurant", "value": "Vejetaryen Restoranı" },
  { "key": "vietnamese_restaurant", "value": "Vietnam Restoranı" },
  { "key": "wine_bar", "value": "Şarap Barı" },
  { "key": "administrative_area_level_1", "value": "Yönetim Alanı Seviye 1" },
  { "key": "administrative_area_level_2", "value": "Yönetim Alanı Seviye 2" },
  { "key": "country", "value": "Ülke" },
  { "key": "city_hall", "value": "Belediye Binası" },
  { "key": "courthouse", "value": "Adliye Sarayı" },
  { "key": "embassy", "value": "Büyükelçilik" },
  { "key": "fire_station", "value": "İtfaiye İstasyonu" },
  { "key": "government_office", "value": "Hükümet Ofisi" },
  { "key": "neighborhood_police_station", "value": "Mahalle Polis Karakolu" },
  { "key": "police", "value": "Polis Merkezi" },
  { "key": "post_office", "value": "Postane" },
  { "key": "chiropractor", "value": "Kayropraktör" },
  { "key": "dental_clinic", "value": "Diş Kliniği" },
  { "key": "dentist", "value": "Diş Hekimi" },
  { "key": "doctor", "value": "Doktor" },
  { "key": "drugstore", "value": "Eczane" },
  { "key": "hospital", "value": "Hastane" },
  { "key": "massage", "value": "Masaj Salonu" },
  { "key": "medical_lab", "value": "Tıbbi Laboratuvar" },
  { "key": "physiotherapist", "value": "Fizyoterapist" },
  { "key": "sauna", "value": "Sauna" },
  { "key": "skin_care_clinic", "value": "Cilt Bakım Kliniği" },
  { "key": "spa", "value": "Spa Merkezi" },
  { "key": "tanning_studio", "value": "Bronzlaşma Stüdyosu" },
  { "key": "wellness_center", "value": "Sağlık Merkezi" },
  { "key": "yoga_studio", "value": "Yoga Stüdyosu" },
  { "key": "apartment_building", "value": "Apartman Binası" },
  { "key": "apartment_complex", "value": "Apartman Kompleksi" },
  { "key": "condominium_complex", "value": "Konut Kompleksi" },
  { "key": "housing_complex", "value": "Konut Alanı" },
  { "key": "bed_and_breakfast", "value": "Oda ve Kahvaltı" },
  { "key": "budget_japanese_inn", "value": "Bütçe Dostu Japon Hanı" },
  { "key": "campground", "value": "Kamp Alanı" },
  { "key": "camping_cabin", "value": "Kamp Kulübesi" },
  { "key": "cottage", "value": "Kulübe" },
  { "key": "extended_stay_hotel", "value": "Uzun Süreli Konaklama Oteli" },
  { "key": "farmstay", "value": "Çiftlik Konaklaması" },
  { "key": "guest_house", "value": "Misafirhane" },
  { "key": "hostel", "value": "Hostel" },
  { "key": "hotel", "value": "Otel" },
  { "key": "inn", "value": "Han" },
  { "key": "japanese_inn", "value": "Japon Hanı" },
  { "key": "lodging", "value": "Konaklama" },
  { "key": "mobile_home_park", "value": "Mobil Ev Parkı" },
  { "key": "motel", "value": "Motel" },
  { "key": "private_guest_room", "value": "Özel Misafir Odası" },
  { "key": "resort_hotel", "value": "Tatil Köyü Oteli" },
  { "key": "rv_park", "value": "Karavan Parkı" },
  { "key": "beach", "value": "Plaj" },
  { "key": "church", "value": "Kilise" },
  { "key": "hindu_temple", "value": "Hindu Tapınağı" },
  { "key": "mosque", "value": "Cami" },
  { "key": "synagogue", "value": "Havra" },
  { "key": "astrologer", "value": "Astrolog" },
  { "key": "barber_shop", "value": "Berber Dükkanı" },
  { "key": "beautician", "value": "Güzellik Uzmanı" },
  { "key": "beauty_salon", "value": "Güzellik Salonu" },
  { "key": "body_art_service", "value": "Vücut Sanatı Hizmeti" },
  { "key": "catering_service", "value": "Yemek Hizmeti" },
  { "key": "cemetery", "value": "Mezarlık" },
  { "key": "child_care_agency", "value": "Çocuk Bakım Ajansı" },
  { "key": "consultant", "value": "Danışman" },
  { "key": "courier_service", "value": "Kurye Hizmeti" },
  { "key": "electrician", "value": "Elektrikçi" },
  { "key": "florist", "value": "Çiçekçi" },
  { "key": "food_delivery", "value": "Yemek Teslimatı" },
  { "key": "foot_care", "value": "Ayak Bakımı" },
  { "key": "funeral_home", "value": "Cenaze Evi" },
  { "key": "hair_care", "value": "Saç Bakımı" },
  { "key": "hair_salon", "value": "Kuaför Salonu" },
  { "key": "insurance_agency", "value": "Sigorta Ajansı" },
  { "key": "laundry", "value": "Çamaşırhane" },
  { "key": "lawyer", "value": "Avukat" },
  { "key": "locksmith", "value": "Çilingir" },
  { "key": "makeup_artist", "value": "Makyaj Sanatçısı" },
  { "key": "moving_company", "value": "Taşımacılık Şirketi" },
  { "key": "nail_salon", "value": "Tırnak Salonu" },
  { "key": "painter", "value": "Boya Ustası" },
  { "key": "plumber", "value": "Tesisatçı" },
  { "key": "psychic", "value": "Medya" },
  { "key": "real_estate_agency", "value": "Emlak Ajansı" },
  { "key": "roofing_contractor", "value": "Çatı Ustası" },
  { "key": "storage", "value": "Depolama" },
  { "key": "summer_camp_organizer", "value": "Yaz Kampı Organizatörü" },
  { "key": "tailor", "value": "Terzi" },
  { "key": "telecommunications_service_provider", "value": "Telekomünikasyon Hizmet Sağlayıcısı" },
  { "key": "tour_agency", "value": "Tur Ajansı" },
  { "key": "tourist_information_center", "value": "Turist Bilgilendirme Merkezi" },
  { "key": "travel_agency", "value": "Seyahat Acentesi" },
  { "key": "veterinary_care", "value": "Veteriner Kliniği" },
  { "key": "asian_grocery_store", "value": "Asya Marketi" },
  { "key": "auto_parts_store", "value": "Oto Yedek Parça Dükkanı" },
  { "key": "bicycle_store", "value": "Bisiklet Dükkanı" },
  { "key": "book_store", "value": "Kitapçı" },
  { "key": "butcher_shop", "value": "Kasap" },
  { "key": "cell_phone_store", "value": "Cep Telefonu Dükkanı" },
  { "key": "clothing_store", "value": "Giyim Mağazası" },
  { "key": "convenience_store", "value": "Bakkal" },
  { "key": "department_store", "value": "Büyük Mağaza" },
  { "key": "discount_store", "value": "İndirim Mağazası" },
  { "key": "electronics_store", "value": "Elektronik Mağazası" },
  { "key": "food_store", "value": "Gıda Marketi" },
  { "key": "furniture_store", "value": "Mobilya Mağazası" },
  { "key": "gift_shop", "value": "Hediye Dükkanı" },
  { "key": "grocery_store", "value": "Market" },
  { "key": "hardware_store", "value": "Hırdavatçı" },
  { "key": "home_goods_store", "value": "Ev Eşyaları Mağazası" },
  { "key": "home_improvement_store", "value": "Ev Geliştirme Mağazası" },
  { "key": "jewelry_store", "value": "Kuyumcu" },
  { "key": "liquor_store", "value": "İçki Dükkanı" },
  { "key": "market", "value": "Pazar" },
  { "key": "pet_store", "value": "Evcil Hayvan Mağazası" },
  { "key": "shoe_store", "value": "Ayakkabı Mağazası" },
  { "key": "shopping_mall", "value": "Alışveriş Merkezi" },
  { "key": "sporting_goods_store", "value": "Spor Malzemeleri Mağazası" },
  { "key": "store", "value": "Mağaza" },
  { "key": "supermarket", "value": "Süpermarket" },
  { "key": "warehouse_store", "value": "Depo Mağazası" },
  { "key": "wholesaler", "value": "Toptancı" },
  { "key": "arena", "value": "Arena" },
  { "key": "athletic_field", "value": "Spor Sahası" },
  { "key": "fishing_charter", "value": "Balıkçılık Tur Hizmeti" },
  { "key": "fishing_pond", "value": "Balık Göleti" },
  { "key": "fitness_center", "value": "Fitness Merkezi" },
  { "key": "golf_course", "value": "Golf Sahası" },
  { "key": "gym", "value": "Spor Salonu" },
  { "key": "ice_skating_rink", "value": "Buz Pateni Pisti" },
  { "key": "playground", "value": "Oyun Parkı" },
  { "key": "ski_resort", "value": "Kayak Merkezi" },
  { "key": "stadium", "value": "Stadyum" },
  { "key": "swimming_pool", "value": "Yüzme Havuzu" },
  { "key": "airport", "value": "Havalimanı" },
  { "key": "airstrip", "value": "Uçak pisti" },
  { "key": "bus_station", "value": "Otobüs terminali" },
  { "key": "bus_stop", "value": "Otobüs durağı" },
  { "key": "ferry_terminal", "value": "Feribot terminali" },
  { "key": "heliport", "value": "Heliport" },
  { "key": "international_airport", "value": "Uluslararası havalimanı" },
  { "key": "light_rail_station", "value": "Hafif raylı sistem istasyonu" }
]

export default placeTypes
